language: node_js

sudo: true

env:
  global:
    - NODE_ENV="production"

node_js:
  - "8"

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential

install:
  - npm config set ttfautohint:force-compile true
  - npm i

script:
  - test -e ./bin/ttfautohint || exit 1

cache:
  directories:
    - $HOME/.npm/enteocode/ttfautohint/tar
